#!/bin/sh

# python: Auto-check for pep8 so I don't check in bad code
FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -e '\.py$')
if [ -n "$FILES" ]; then
    flake8 $FILES
fi

# go: Auto-check for golint and go vet
FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -e '\.go$')
if [ -n "$FILES" ]; then
    golint $FILES
		go vet $FILES
fi
